export {default as Navbar}from "./Navbar"
export {default as Socials}from "./Socials"
export {default as Footer}from "./Footer"
export {default as MobileNav}from "./MobileNav"
export {default as Carousel}from "./Carousel"